### ISSUE TITLE
catch2 version 3?

### ISSUE THREAD

**Issue by traversaro** [conda-forge/catch2-feedstock#49]
### Comment:

Hi @conda-forge/catch2, thanks a lot for your work! 

I noticed that catch version 3 was released (see https://github.com/conda-forge/catch2-feedstock/pull/48), but the recipe is still called `catch2`. Is this intentional? Could it make sense to change the name of the package?

Thanks in advance.

**Comment by traversaro** [comment]
By looking at the files installed, it seems that che CMake package continues to be called Catch2, the library libCatch2.a and the headers `include/catch2/<name>.hpp`, so I think it make sense for the package to be called catch2, even if it is confusing.

**Comment by tdegeus** [comment]
On first sight I also found this confusing. I think that `Catch2` is just the name, not a v2 of `Catch`. I.e. there was also a `Catch2` v1.

**Comment by tdegeus** [comment]
(I cannot work out what the name signifies, not that that matters)

**Comment by traversaro** [comment]
Yes, I totally agrees. At least this issue may be useful for people that have the same doubt in the future.
