### ISSUE TITLE
find_package(Catch2) is not working in Linux because of lib64 instead of lib

### ISSUE THREAD

**Issue by allanleal** [conda-forge/catch2-feedstock#6]
After installing catch2 with conda, I can see the following directory in my environment:

`/home/username/miniconda3/envs/envname/lib64/cmake/Catch2/`

with the following files

~~~
Catch2Config.cmake
Catch2ConfigVersion.cmake
Catch2Targets.cmake
CatchAddTests.cmake
Catch.cmake
ParseAndAddCatchTests.cmake
~~~

However, cmake **is unable to find** `Catch2Config.cmake`, despite the [documentation of `find_package`](https://cmake.org/cmake/help/latest/command/find_package.html) indicate that this path is searchable by cmake (provided one appends `$ENV{CONDA_PREFIX}` to `CMAKE_PREFIX_PATH`).

Copying the `lib64/cmake/*` dir to `lib/cmake/*` resolves the issue.

I believe this is related to the same bug found by conan community:
https://github.com/bincrafters/community/issues/419

It seems that in the end they forced the use of `lib` instead of `lib64`. 

What about the same is done here?

**Comment by mjscosta** [comment]
@allanleal did you tested the last version I've committed, the one with the cmake test project?

The test is passing in linux, so I'd expect that the in the test the cmake find_package(Catch2 REQUIRED) is successfull.

Do you have issues installing the build 3 of the package ?

**Comment by allanleal** [comment]
The CMake config files of catch2 persists being installed in `lib64`, despite us setting `-DCMAKE_INSTALL_LIBDIR=lib`. Right now, I'm copying the `cmake/Catch2` dir from `lib64` to `lib` (in the env directory) to make it work (a hack I know). I'll see if I can correct this for good in the next days.

**Comment by mjscosta** [comment]
If you really need to set this up, check this cmake template I'm using.
https://github.com/practicalci/cookiecutter-cpp/blob/337cd5ec6fed0c9692cf46bec7b8a1aa579c97fa/%7B%7Bcookiecutter.project_slug%7D%7D/cpp/CMakeLists.txt#L30

Its using conan, and I have catch in the conanfile.txt, I want to move completly to conda, but these catch isses are really consuming too much for me.

**Comment by allanleal** [comment]
Cool - thanks.
